# Site settings
title: pyCI - a minimal CI server
email: tbraun@tnt-web-solutions.de
description: A minimal CI server written in Python.
baseurl: http://tbraun89.github.io/pyCI

# Build settings
markdown: kramdown
